const express = require("express");
const authRoutes = require("./authRoutes");
const productRoutes = require("./productRoutes");
const categoryRoutes = require("./categoryRoutes");
const brandRoutes = require("./brandRoutes");
const supplierRoutes = require("./supplierRoutes");
const memorySizeRoutes = require("./memorySizeRoutes");
const userRoutes = require("./userRoutes");
const cartRoutes = require("./cartRoutes");
const orderRoutes = require("./orderRoutes");
const shippingRoutes = require("./shippingRoutes");
const paymentRoutes = require("./paymentRoutes");
const statsRoutes = require("./statsRoutes");
const promotionRoutes = require("./promotionRoutes");
const router = express.Router();

router.use("/auth", authRoutes);
router.use("/products", productRoutes);
router.use("/categories", categoryRoutes);
router.use("/brands", brandRoutes);
router.use("/suppliers", supplierRoutes);
router.use("/memorysizes", memorySizeRoutes);
router.use("/users", userRoutes);
router.use("/carts", cartRoutes);
router.use("/orders", orderRoutes);
router.use("/shipping", shippingRoutes);
router.use("/payments", paymentRoutes);
router.use("/stats", statsRoutes);
router.use("/promotions", promotionRoutes);

module.exports = router;
